### ISSUE TITLE
ERR_INVALID_URL for es-module-shims when defaultProvider = 'nodemodules'

### ISSUE THREAD

**Issue by zachsa** [jspm/generator#120]
Running the JSPM generator with defaultProvider = 'nodemodules' doesn't work as I expected. I'm using JSPM via the chomp extension - here is the task definition:

```toml
[[task]]
name = 'jspm:react'
dep = 'clients/html/#.html'
target = '.cache/#.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
default-provider = 'nodemodules'
preload = true
integrity = false
```

And I get the following error:

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:563:9)
    at new URL (node:internal/url:643:5)
    at Resolver.resolveLatestTarget (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:927:18)
    at Resolver.resolveLatestTarget (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1425:85)
    at Generator.htmlGenerate (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:2663:58)
    at async file:///home/zach/code/saeon/repositories/somisana/web//[cm]:16:41 {
  input: 'node_modules/es-module-shims',
  code: 'ERR_INVALID_URL'
}

Node.js v18.0.0
```
